Create Segemented trees.cpp
codeIIEST/Algorithms pull request #126
Opened 2017-12-08 07:06 UTC by D3v3sh5ingh

Segmented trees added

2017-12-08 07:48 UTC, prateekiiest commented
please mention the issue no

2017-12-08 07:51 UTC, D3v3sh5ingh commented
Issue # 92

2017-12-09 07:23 UTC, prateekiiest commented
now , you made a good PR.
congrats 👍

2017-12-09 07:25 UTC, prateekiiest requested changes

2017-12-09 07:25 UTC, prateekiiest commented on Competitive Coding/Tree/Binary Tree/Segemented trees.cpp
> +     // the sum of the segment
instead of ss, se use start, end

2017-12-09 07:25 UTC, prateekiiest commented on Competitive Coding/Tree/Binary Tree/Segemented trees.cpp
> +     if (qs < 0 || qe > n-1 || qs > qe)
similarly for qs, qe and st.

2017-12-09 07:26 UTC, prateekiiest commented
please show me the output of this code

2017-12-09 09:59 UTC, D3v3sh5ingh reviewed
Required changes done
Changed variable names for better understanding

2017-12-09 10:00 UTC, D3v3sh5ingh commented
![screenshot 30](https://user-images.githubusercontent.com/31030254/33794647-d3f5d48c-dcf5-11e7-813d-64fe40bef00b.png)

Output of the Code.

2017-12-12 03:12 UTC, closed without merging