Project Euler
codeIIEST/Algorithms pull request #174
Opened 2017-12-12 07:24 UTC by rahulkumaran

Thank you for your contribution. Please provide the details requested below.

## ISSUE NUMBER

#128 

## SHORT DESCRIPTION
Added project euler folder inside math folder in competitive programming. Also added code for problem 20 of project euler

## TESTING

run it and you'll get the answer directly

2017-12-12 14:52 UTC, prateekiiest requested changes
rename it to fractal.py

2017-12-12 15:28 UTC, rahulkumaran commented
@prateekiiest , just renamed it! have a look at it :)

2017-12-14 03:20 UTC, prateekiiest approved these changes

2017-12-14 03:20 UTC, merged

2017-12-14 03:20 UTC, prateekiiest commented
Thanks for the contribution :1st_place_medal: