Added algorithm for detecting cycles
codeIIEST/Algorithms pull request #187
Opened 2017-12-12 18:40 UTC by Jatin86400

## ISSUE NUMBER

https://github.com/codeIIEST/Algorithms/issues/184

## SHORT DESCRIPTION

In this algorithm we detect cycles in the graph by assigning parent to each node and comparing the parent node.

2017-12-13 03:11 UTC, prateekiiest requested changes
readme.md , not readme.txt

and add comments in code

2017-12-13 10:27 UTC, Jatin86400 commented
I have made the changes you said, but I am not able to clear the check, I don't understand why.

2017-12-13 14:21 UTC, prateekiiest commented
you need to check the codacy issues @Jatin86400 
click on the details

2017-12-14 03:33 UTC, prateekiiest approved these changes

2017-12-14 03:33 UTC, merged