Coin change problem
codeIIEST/Algorithms pull request #242
Opened 2017-12-18 12:36 UTC by nandikeshsingh

## ISSUE NUMBER

#241 

## SHORT DESCRIPTION

Coin change problem using dynamic programming in C++.

## TESTING

Passed all the test cases on geeksforgeeks.
![screenshot from 2017-12-18 15-49-58](https://user-images.githubusercontent.com/25327061/34106307-b8397c92-e41d-11e7-9a97-c554c4563ba5.png)

2017-12-24 16:36 UTC, prateekiiest requested changes

2017-12-24 16:36 UTC, prateekiiest commented on Competitive Coding/Dynamic Programming/Coin Change/Coin Change Readme.md
> +Given a value N and the values of different denomination,find the number of ways to make changes for N cents,if we have infinite supply of all denominations.
make problem,input, output and others alike as a heading (### )

2017-12-24 16:36 UTC, prateekiiest commented on Competitive Coding/Dynamic Programming/Coin Change/Coin Change Readme.md
> +Time Complexity : O(N*M)
make language, algorithm paradigm and time complexity bold.

use tilde tag `O(N*M)`

2017-12-24 17:51 UTC, nandikeshsingh commented
updated the readme as needed.

2017-12-24 17:59 UTC, nandikeshsingh commented
changes done as required.

2017-12-24 18:00 UTC, nandikeshsingh commented
updated readme as needed.

2017-12-24 18:04 UTC, nandikeshsingh commented
updated readme as needed.

2017-12-26 02:22 UTC, prateekiiest requested changes

2017-12-26 02:22 UTC, prateekiiest commented on Competitive Coding/Dynamic Programming/Coin Change/Coin Change Readme.md
> +Language : `C++`
don't make language, algo paradigm till space complexity a heading.

use #### to make those a subheading

2017-12-26 02:22 UTC, prateekiiest commented on Competitive Coding/Dynamic Programming/Coin Change/Coin Change Readme.md
> +Another array temp stores the best values for sub-problems.For eg: temp[3][4] stores the optimal value for the number of ways
use `temp[3][4]` before and after using tilde (`).

Similarly for arr[0]., arr[1], ... use tilde `

2017-12-26 17:36 UTC, nandikeshsingh commented
updated readme.md

2017-12-28 17:14 UTC, prateekiiest approved these changes

2017-12-28 17:15 UTC, merged