Myone
codeIIEST/Algorithms pull request #251
Opened 2017-12-20 11:45 UTC by Priyangshuyogi

## ISSUE NUMBER - #185 

## SHORT DESCRIPTION
Consist of various methods to find a number is prime or not.

## LOCATION
 I am including this in a folder named Primality Test in math folder inside Competitive programming. 

##INSIDE

All these methods are described in its perspective README.md and the implementation part is in the ScrCode.cpp file.

2017-12-20 12:52 UTC, prateekiiest commented
Please specify the issue name

2017-12-20 13:02 UTC, Priyangshuyogi commented
Issue  #185 , interesting math algo in Competitive programming.

2017-12-20 13:08 UTC, prateekiiest commented
edit the issue name pls

2017-12-20 13:29 UTC, Priyangshuyogi commented
Ok it is done.

2017-12-26 15:54 UTC, Priyangshuyogi commented
@prateekiiest long time no see.

2017-12-28 17:11 UTC, prateekiiest requested changes
Just a few comments.

looks good though ㊗️ 🎆

2017-12-28 17:11 UTC, prateekiiest commented on Competitive Coding/Math/Primality Test/Fermat Method/README.md
> +a^n-1 ≡ 1 (mod n)
add a tilde here like this `a^n-1 = 1 mod(n)`

2017-12-28 17:11 UTC, prateekiiest commented on Competitive Coding/Math/Primality Test/Optimized School Method/README.md
> +
make all input / output bold and tilde for  n assignment

2017-12-28 17:11 UTC, prateekiiest commented on Competitive Coding/Math/Primality Test/Optimized School Method/README.md
> +Time complexity of this solution is O(√n).
`O(root(n))`

2017-12-29 07:33 UTC, Priyangshuyogi commented
is it all ok now??

2017-12-29 08:20 UTC, baolao commented
Yes thank you 

Sent from my iPhone

> On Dec 29, 2017, at 2:33 AM, Priyangshu yogi <notifications@github.com> wrote:
> 
> is it all ok now??
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-12-29 09:44 UTC, prateekiiest commented on Competitive Coding/Math/Primality Test/Fermat Method/README.md
> +a^n-1 = 1 mod (n)
use tilde here ``

2017-12-29 09:44 UTC, prateekiiest commented on Competitive Coding/Math/Primality Test/Fermat Method/README.md
> +a^n-1 % n = 1
also here

2018-01-01 15:31 UTC, Priyangshuyogi commented
Is it okay??

2020-07-05 11:12 UTC, prateekiiest commented
Sorry for the so long delay.

2020-07-05 11:12 UTC, merged