HeapSort, RadixSort and BucketSort
codeIIEST/Algorithms pull request #68
Opened 2017-12-02 19:55 UTC by AdvikEshan

i have added three sorting programs of HeapSort, RadixSort and BucketSort written in C++

2017-12-03 05:25 UTC, prateekiiest requested changes

2017-12-03 05:25 UTC, prateekiiest commented on sort/BucketSort.cpp
> +for(i=0;i<n;i++){
document the code for understanding

2017-12-03 05:25 UTC, prateekiiest commented on sort/BucketSort.cpp
> +    buckets[(int)(n*a[i])].push_back(a[i]);
I didn't get this line. can you elaborate?

2017-12-03 05:25 UTC, prateekiiest commented on sort/HeapSort.cpp
> +//Runs in O(logN) , floats down value at index i until a[i] becomes a max heap
dont write complexities here, write in a separate readme

2017-12-03 05:25 UTC, prateekiiest commented on sort/RadixSort.cpp
> +for(int exp=1;m/exp > 0; exp=exp*10){
could you pls explain why exponential is being used in this case?

2017-12-03 05:25 UTC, prateekiiest commented on sort/RadixSort.cpp
> +    for(i=0;i<n;i++){
document code pls

2017-12-03 05:26 UTC, prateekiiest commented
please make sure you make a separate folder for all the code. Like for heapsort make a folder named heapsort and there you add the code and a readme for the analysis.
Same for radix, bucket.

And see the review

2017-12-03 05:29 UTC, AdvikEshan commented
Ok sir,  i have got it... I'll fix it soon!

On Dec 3, 2017 10:56, "Prateek Chanda" <notifications@github.com> wrote:

> please make sure you make a separate folder for all the code. Like for
> heapsort make a folder named heapsort and there you add the code and a
> readme for the analysis.
> Same for radix, bucket.
>
> And see the review
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/codeIIEST/Algorithms/pull/68#issuecomment-348741538>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AWea6Z0Kdn1q3m-apa4JkaaPMLijxYoMks5s8jERgaJpZM4QzcOu>
> .
>

2017-12-03 06:44 UTC, prateekiiest commented on sort/HeapSort/Readme
> +1 A.heap-size = A.length
dont include the algo pseudo code here

2017-12-03 06:45 UTC, prateekiiest reviewed
dont include the algo pseudo code here

2017-12-03 07:01 UTC, AdvikEshan commented
ohk sir, I hav removed it.
Now plz have a look on it once again

On 3 December 2017 at 12:15, Prateek Chanda <notifications@github.com>
wrote:

> *@prateekiiest* commented on this pull request.
>
> dont include the algo pseudo code here
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/codeIIEST/Algorithms/pull/68#pullrequestreview-80693312>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AWea6T8jNukm2IgOQLA7Op5GdUhSsivJks5s8kOVgaJpZM4QzcOu>
> .
>

2017-12-03 07:05 UTC, AdvikEshan commented
If this format is ok then I'll upload further in this format only...Thus
please check it once !!

On 3 December 2017 at 12:31, Kumar Nitish <kumarnitish1996@gmail.com> wrote:

> ohk sir, I hav removed it.
> Now plz have a look on it once again
>
> On 3 December 2017 at 12:15, Prateek Chanda <notifications@github.com>
> wrote:
>
>> *@prateekiiest* commented on this pull request.
>>
>> dont include the algo pseudo code here
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/codeIIEST/Algorithms/pull/68#pullrequestreview-80693312>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AWea6T8jNukm2IgOQLA7Op5GdUhSsivJks5s8kOVgaJpZM4QzcOu>
>> .
>>
>
>

2017-12-04 12:50 UTC, abiduzz420 commented on sort/HeapSort/HeapSort.cpp
> +int a[]={5,1,2,0,6};
It would be good if you can dynamically allocate the array @AdvikEshan

2017-12-04 18:27 UTC, AdvikEshan commented
I'll change it by tomorrow... Thanx!

2017-12-05 06:54 UTC, AdvikEshan commented
Sir, Change has been made to HeapSort (Array is allocated dynamically) !! Have a look !

2017-12-05 07:08 UTC, abiduzz420 commented
@AdvikEshan You are still declaring array as `int a[20]`. That's not dynamic memory allocation

2017-12-05 07:13 UTC, AdvikEshan commented
Oh Sorry, i have got the wrong meaning ! My mistake !! I'll change it soon.

2017-12-05 17:28 UTC, AdvikEshan commented
Now, I have updated it...Have a look @abiduzz420 @prateekiiest  !! #68

2017-12-06 08:33 UTC, soubh1k commented
I am closing this pull request. The current directory structure has been changed. Fork the new repo with the new directory structure. Insert the files in the new directory structure along with the appropriate readme's. Then create a new Pull Request.

2017-12-06 08:33 UTC, closed without merging